[theme]
base = "light"
primaryColor = "#8B5CF6"
backgroundColor = "#F6F3FC"
secondaryBackgroundColor = "#F0EAFB"
textColor = "#3B3560"
font = "sans serif"

[server]
runOnSave = true
headless = false

[browser]
gatherUsageStats = false
